### PR TITLE
Updates for first-order states and mode-shape visualization

### PR DESCRIPTION
**Pull request by bjonkman**

### CODE REVIEW

**Comment by rafmudaf** [comment]
@bjonkman @ebranlard do either of you have any comments on this or can I hit the merge button?

**Comment by bjonkman** [comment]
@rafmudaf: You might want to ask Nick Johnson if it's doing what he expects before merging it.

**Comment by rafmudaf** [comment]
Ok thanks for the heads up

**Comment by bjonkman** [comment]
FYI, Nick told me today that this is working.

**Pull request merged**
